services:
  db:
    image: postgres:15.2-bullseye
    expose:
      - 5432
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${DB_DATABASE_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    env_file:
      - .env
    networks:
      internal:

    volumes:
      - postgres-data:/var/lib/postgresql/data


networks:
  internal:
    driver: bridge

volumes:
  postgres-data:
    name: "todoaholic-api-postgres-data"
